name: clang-tidy-review

on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          dir: ${{github.workspace}}
        
      - name: Create compile_commands.json
        run: |
          cmake . -B '${{github.workspace}}/build' -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          
      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.6.1
        id: review
        with:
          build_dir: build
